pipeline {

    agent any

    parameters {

        string(
            name: 'PROJECT_URL',
            defaultValue: '',
            description: 'Python project Git URL'
        )

        choice(
            name: 'PYTHON_VERSION',
            choices: [
                'python3.8',
                'python3.9',
                'python3.10',
                'python3.11',
                'python3.12'
            ],
            description: 'Python version'
        )

        choice(
            name: 'ENVIRONMENT',
            choices: [
                'DEV',
                'PROD'
            ],
            description: 'Environment'
        )
    }

    stages {

        stage('Template Test') {

            steps {

                echo "===================================="
                echo "Python Application Template"
                echo "===================================="

                echo "Project URL : ${params.PROJECT_URL}"
                echo "Python      : ${params.PYTHON_VERSION}"
                echo "Environment : ${params.ENVIRONMENT}"

                sh '''
                    python3 --version || true
                '''
            }
        }
    }
}