pipelineJob('python-app-template') {

    description('''
        Production Python Application Template

        Generated by Jenkins Job DSL.
        Jenkinsfile is maintained in GitHub.
    ''')

    parameters {

        stringParam(
            'PROJECT_URL',
            '',
            'Git repository URL of the Python application'
        )

        choiceParam(
            'PYTHON_VERSION',
            [
                'python3.8',
                'python3.9',
                'python3.10',
                'python3.11',
                'python3.12'
            ],
            'Python version'
        )

        choiceParam(
            'ENVIRONMENT',
            [
                'DEV',
                'PROD'
            ],
            'Deployment environment'
        )
    }

    definition {

        cpsScm {

            scm {

                git {

                    remote {
                        url('https://github.com/brijeshkori-lab/Jenkins-library.git')
                    }

                    branch('*/template')
                }
            }

            scriptPath('python-template/Jenkinsfile')

            lightweight(true)
        }
    }
}