pipelineJob('Python-App-With-Sonar') {

    description("""
        ================================================
        Python Application CI/CD Template
        ================================================

        Reusable Jenkins pipeline for Python applications.

        Features:
        - Multiple Python versions
        - Git checkout
        - Virtual environment
        - Dependency installation
        - Unit testing
        - Coverage
        - SonarQube
        - JFrog
        - Production approval
        - Release Bundle

        This job is generated by the Python Job Template.
        ================================================
    """)

    logRotator {
        numToKeep(20)
        artifactNumToKeep(10)
    }

    parameters {

        stringParam(
            'PROJECT_URL',
            '',
            'Git repository URL'
        )

        choiceParam(
            'PYTHON_VERSION',
            [
                'python3.10',
                'python3.11',
                'python3.12'
            ],
            'Python version'
        )

        stringParam(
            'SONAR_PROJECT_KEY',
            '',
            'SonarQube project key'
        )

        choiceParam(
            'ENVIRONMENT',
            [
                'DEV',
                'PROD'
            ],
            'Target environment'
        )

        choiceParam(
            'IS_FINAL_RUN',
            [
                'false',
                'true'
            ],
            'Production final run'
        )

        stringParam(
            'JFROG_REPOSITORY',
            'python-local',
            'JFrog repository'
        )

        stringParam(
            'PRIMARY_APPROVER_EMAIL',
            '',
            'Primary production approver'
        )

        stringParam(
            'MANAGER_EMAIL',
            '',
            'Manager email'
        )

        stringParam(
            'TO_EMAIL',
            '',
            'Notification recipients'
        )

        stringParam(
            'CC_EMAIL',
            '',
            'CC recipients'
        )
    }

    definition {

        cps {

            script(
                new File(
                    build.getWorkspace().toString(),
                    'Jenkinsfile'
                ).text
            )

            sandbox()
        }
    }
}